# Generated by Django 4.1.1 on 2022-09-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
