# Generated by Django 4.1.1 on 2022-10-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_decoration'),
    ]

    operations = [
        migrations.AddField(
            model_name='decoration',
            name='picture',
            field=models.ImageField(null=True, upload_to='upload/decoration'),
        ),
    ]
