# Generated by Django 4.1.1 on 2022-10-12 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='member',
        ),
    ]
